### ISSUE TITLE
Knowledge Milestone on BST

### ISSUE THREAD

**Issue by tjklint** [tjklint/leetcode#11]
### Milestone Description
Implementing search and delete operations in a Binary Search Tree (BST) using both recursive and iterative approaches, aimed at preparing for a final exam.

### Tasks
- [ ] [Implement recursive search in a BST.](https://github.com/tjklint/leetcode/issues/8)
- [ ] [Implement iterative search in a BST.](https://github.com/tjklint/leetcode/issues/8)
- [ ] [Implement recursive deletion from a BST.](https://github.com/tjklint/leetcode/issues/9)
- [ ] [Implement iterative deletion from a BST.](https://github.com/tjklint/leetcode/issues/9)

### Additional context
These tasks will help in gaining a thorough understanding of search and deletion operations in BSTs, essential for the final exam preparation.
